### ISSUE TITLE
Setting "listen_key_toggle":None, gives error

### ISSUE THREAD

**Issue by larsss83** [jwebmeister/tacspeak#11]
The None option for listen key toggle dosent seem to work anymore.. I'm getting this error: "engine (WARNING): Exception while initializing kaldi engine: Invalid listen_key_toggle. 0 for toggle mode off; 1 for toggle mode on; 2 for global toggle on (use VAD); -1 for toggle mode off but allow priority grammar"

**Comment by jwebmeister** [comment]
Whoops! Shows you how often I've used it personally. 

I think it never worked for anyone, because that the instructions are wrong. Instructions should be:

- `listen_key` should be set to `None`, overriding `listen_key_toggle`, and setting it into always listening mode.   
- `listen_key_toggle` can remain as -1, 0, 1, 2, just `listen_key` needs to be set to None.

I'll update readme. 

Thank you :)

**Comment by jwebmeister** [comment]
Done! [updated readme - fixed "always listening mode" instructions](https://github.com/jwebmeister/tacspeak/commit/bdd7193987235244e166d44446d1c2af94481696)
