### ISSUE TITLE
Program is classified as a virus by Windows Defender on Windows 11. 

### ISSUE THREAD

**Issue by shoul** [jwebmeister/tacspeak#17]
I have used the program for a few days without any problems. Without any changes to the program or system, "tacspeak.exe" was then classified as a virus, moved to quarantine and deleted. A re-installation is not possible because it leads to the same result.  

The following link leads to a request and a solution from a developer with similar problems:
https://answers.microsoft.com/en-us/windows/forum/all/my-software-is-wrongly-beeing-flagged-as-virus/124f6a62-6f88-4235-9f80-975c01a16198

**Comment by jwebmeister** [comment]
Is it just the .exe being quarantined?

**Comment by adenlim** [comment]
<img width="367" alt="image" src="https://github.com/jwebmeister/tacspeak/assets/64777089/86a3ce3a-95d2-40a4-9bbc-27bed1fa9278">

currently windows defender believe that the .exe file contains Trojan:Win32/Wacatac.B!ml

**Comment by jwebmeister** [comment]
For now, I suggest adding `<specific directory>/tacspeak.exe` as an exclusion to Windows Defender, and make sure you're downloading tacspeak from a trusted source (this repo or the nexusmods mod page).  
Concerned users can review and build from source themselves, and/or check the [VirusTotal report here](https://www.virustotal.com/gui/file/41ad83dc93ebabc0187de45f6deb451b24d0d900c793ea618aea4d7d42e24c86/detection)

**Comment by jwebmeister** [comment]
I should've said this earlier, but thank you for raising it as an issue, and for providing a helpful link.  

I can confirm I can reproduce the issue with Microsoft Defender, but only on Windows 11, not 10 (for now). 

I've put in a submission to Microsoft to review "tacspeak.exe", so hopefully Defender will stop flagging it as a trojan "soon". 

Otherwise, for now, I suggest adding "tacspeak.exe" as an exclusion in Defender, and make sure you only download Tacspeak from [this repo](https://github.com/jwebmeister/tacspeak) or [nexusmods mod page](https://www.nexusmods.com/readyornot/mods/3159).

**Comment by jwebmeister** [comment]
Also, anyone can download the source code and build the Tacspeak application themselves.  Or, run it from Python.  All the instructions are in the readme.

**Comment by jwebmeister** [comment]
After updating the definitions + running the commands quoted above, I get no threats detected from Windows Defender when running a scan on the Tacspeak folder (including tacspeak.exe).  

Can someone else please confirm they receive no more flags from Defender on their system (after definition updates and/or commands run), that the issue's resolved and can be closed? @shoul @adenlim

**Comment by jwebmeister** [comment]
Commenter on YouTube stated it was no longer flagging after updating definitions and redownloading Tacspeak. Closing issue.
