### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Icyblue2208** [jwebmeister/tacspeak#19]
My game crashes only when using tecspeak speech recognition on READY OR NOT ive tried all the troubleshooting nothing works and im wondering if theres any fix .

**Comment by jwebmeister** [comment]
Need more info. Things to check:
- is just ready or not crashing? Is anything else affected?
- are you starting ready or not vs tacspeak first? Have you tried the other way around?
- Does tacspeak and ready or not run stable and correctly when the other is not running? e.g. can play a mission, can get tacspeak to recognise “freeze” and other commands when `DEBUG_MODE = True` in `user_settings.py`
- open task manager, watch your RAM usage, run both tacspeak and ready or not, are you running out of memory?
- Is there any useful info in the .log file? You should attach it to this issue.
- check windows sound settings, including “exclusive” settings (mentioned in troubleshooting section)
- do you have any conflicting software, mods, etc?
- do either tacspeak or ready or not, not have windows “permission” to access your microphone?

**Comment by Icyblue2208** [comment]
Everything works it’s just when I use tacspeak ready or not crashes when it
boots up. And yes if tried it the other way around it still crashes

**Comment by Icyblue2208** [comment]
My ram usage is really high is from around 60-80.

**Comment by jwebmeister** [comment]
> My ram usage is really high is from around 60-80. And ready or not is the only one crashing nothing else. It says that i ran out of video memory but i have enough video mem and ram memory.

If it's saying it ran out of memory, that's probably the reason. 

Would ~2GB send it over or very close to 100%? Tacspeak on first load tries to allocate ~2GB of RAM. 

If there isn't enough freely available memory when it (or any program) tries to allocate it, your system will try to do some memory rearrangement and may freeze up while it figures out how to make room. This is usually fine for most applications, but a real-time + performance critical + resource intensive application, like a FPS game, usually "optimise out" some safeguards to get better performance. 

I don't know for *certain* if this is the root cause, but there was a reason I asked you to look at RAM usage from the beginning. There's very few things that Tacspeak could possibly do to *cause* a crash, it's only indirectly, competing for resources from the OS. Prime suspects are:

1. Your systems resources are limited and can't handle both running at once; games are notoriously sensitive to being starved of resources.
2. There's some conflict or competition in trying to access your microphone; though if this were the case, Tacspeak would show an error message indicating it's something audio related, or crash itself.

Try closing other applications to free up resources before playing. This should also reduce the chance of other applications causing conflicts. You could also consider hardware upgrades.

Is there any other information that you can think of that could help troubleshoot the issue any further?

**Comment by Icyblue2208** [comment]
No its all fixed i just added more ram in thank you.
