### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by Icyblue2208** [jwebmeister/tacspeak#20]
Tacspeak keeps crashing when I open it and the troubleshooting's aren't working and i think i 
have all the files downloading in the right [location. Please help thank you.

**Comment by Icyblue2208** [comment]
![Desktop Screenshot 2024 01 07 - 17 47 48 80](https://github.com/jwebmeister/tacspeak/assets/155859891/07e50df9-3bd3-4f46-bc1f-2631dffe5b20)

**Comment by jwebmeister** [comment]
Try:
- Reinstall Tacspeak + model, don't change any settings (keep it all default)
- Restart your pc
- Check your windows sound settings, including exclusive mode 
- pretty much everything else in the troubleshooting section

Almost every reported crash / exit on startup has been because of missing files or corrupt user settings. The exception being  windows sound settings and/or external software not sharing access to the microphone.

Once you've gone through everything in the troubleshooting section, and if still having issues, run `tacspeak.exe --print_mic_list` and tell me what the microphone & interface is (it will have an > sign next to it). See issue #2 for more info

**Comment by jwebmeister** [comment]
Also please attach the actual log file. Some of the text is cut off which might contain useful information.

**Comment by Icyblue2208** [comment]
I cant attach it because it crashes before i can see anything.

**Comment by jwebmeister** [comment]
What was the root cause?

You can run command prompt or powershell first, then run tacspeak.exe within the console to be able to see the messages even after it exits. 

There also should be a .tacspeak.log file in the same folder as tacspeak.exe, though sometimes there won't be one if it crashes / exits early enough.
