### ISSUE TITLE
Program detects microphone input but not sending key inputs

### ISSUE THREAD

**Issue by Pichulol** [jwebmeister/tacspeak#32]
When running the program it detects what i say and is able to print back what I say when I turn on debug mode. Even though the keywords are being detected it still doesnt press any of the corresponding keys to it. So for example I would say "Police" i get "on_recognition (INFO): KaldiRule(16, ReadyOrNot_priority::YellFreeze) | police
on_recognition (INFO): KaldiRule(16, ReadyOrNot_priority::YellFreeze) | police
Freeze!
(kb_f)" 
But in game it isnt doing the bind for it

**Comment by jwebmeister** [comment]
To be clear, with debug mode on, virtual key presses are disabled; you need to turn off debug mode for any virtual key presses to be sent to the game. Otherwise:
- Check your keybinds in-game, test physical button presses work.
- Check your keybinds in Tacspeak (./tacspeak/grammar/_readyornot.py).
- Make sure [Microsoft Visual C++ Redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe) is installed
- Check if there's any other programs that might be interfering with keypresses (e.g. TrackIR, overlays, etc).
- Go through the troubleshooting section in the README.md file.

**Comment by Pichulol** [comment]
I checked all of these and it still isnt pressing buttons. Turned off debug mode, binds are correct, Tacspeak has the right binds, Visual C++ redistributable is installed, No overlays or programs are interfering with keypresses, and nothing in the troubleshooting section helped my issue.

**Comment by jwebmeister** [comment]
Ok. If I'm understanding correctly (let me know if that's not the case):
- the speech recognition is working a-ok, just virtual key presses aren't being sent.
- all of the troubleshooting steps have already been attempted, including running as admin, nothing worked.

Next steps to try:
1. Re-install Tacspeak, leave everything as default.
2. Test again with debug mode off, Ready or Not + Tacspeak running, say a few different commands, then attach to this issue the `.tacspeak.log` file.
3. (optional) test using notepad
    a. rename `./tacspeak/grammar/dontload_testnotepad.py` to `_testnotepad.py` (keep in the same folder)
    b. Run notepad + Tacspeak
    c. Speak a few commands including "turtle" and "bear", it should print the text in notepad.
    d. Dictate some phrases, whatever you want, it should print the text in notepad, e.g. "Computer, why do you hate us?"
    e. Close notepad + Taspeak
    f. Rename `./tacspeak/grammar/_testnotepad.py` to `dontload_testnotepad.py` (keep in the same folder)
    g. Comment in this issue if you had any success or not.

**Comment by Pichulol** [comment]
So I reinstalled and it still doesnt work with Ready Or Not. I tried the notepad one and that worked fine.

**Comment by Pichulol** [comment]
[.tacspeak.log](https://github.com/user-attachments/files/16685008/default.tacspeak.log)

Here is also the log file that has the first time where i tried it with ready or not, then tried the notepad way, then tried again with ready or not

**Comment by jwebmeister** [comment]
Try changing in `./tacspeak/user_settings.py` (all other settings as default):

1. `USE_NOISE_SINK = False`
2. `"listen_key_toggle":0,`

Then try again both notepad (follow steps in my previous comment) and Ready or Not, let me know if it works or not.

Also is your OS Windows 10 or 11?

**Comment by Pichulol** [comment]
Notepad works still but ready or not doesnt. Im using Windows 10

**Comment by jwebmeister** [comment]
Very strange. Based on your testing and comments, there's only a few likely causes for the issue (other than what's already described in the troubleshooting section):

1. There's some issue with Tacspeak recognising that the game is running & focussed, specifically [this line of code](https://github.com/jwebmeister/tacspeak/blob/main/tacspeak/grammar/_readyornot.py#L45). 
    a. Is the game running from an executable named "ReadyOrNot*.exe" (where * is none or any number of characters)?
    b. Is there some overlay (e.g. Steam, OBS, Nvidia, etc) tricking Tacspeak (and Windows) that it's the focussed window and not the game?
    c. You're testing it with the game window focussed? i.e. the mouse cursor is clicked in the game.
    d. **Try changing [this line of code](https://github.com/jwebmeister/tacspeak/blob/main/tacspeak/grammar/_readyornot.py#L45)** in "./tacspeak/grammar/_readyornot.py" from `grammar_context = AppContext(executable="ReadyOrNot")` to `grammar_context = AppContext()` note: don't remove the preceding indentation! This will make the Ready Or Not commands active whenever you start Tacspeak, even if the game isn't running or focussed.
2. Your game is below 30 fps, the CPU isn't coping with both Tacspeak and game running, and it's affecting speech recognition. 
    a. If Tacspeak is recognising the commands _with the game running_ (as you said with debug mode on, but need to confirm you had the game running), then this isn't the cause of the issue. 
    b. You can try changing the `min_delay` (see [this line of code](https://github.com/jwebmeister/tacspeak/blob/main/tacspeak/grammar/_readyornot.py#L62)) if the keys aren't being pressed, but based on the log file, it seems like there's no speech command recognition with the game running (without debug mode is on).

Try what's described in 1.d. let me know how it goes.  
If that does (or doesn't) fix it, and if you can figure it out, I'd like to know what's the root cause of the issue.

**Comment by Pichulol** [comment]
doing 1d helped the issue. I am now able to use the program with Ready or Not. Thank you for helping!
